# Generated by Django 4.2.7 on 2024-01-07 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userlist', '0002_alter_userlist_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='malefemale',
            name='sex',
            field=models.CharField(max_length=1, unique=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='dob',
            field=models.DateField(blank=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='first_name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='last_name',
            field=models.CharField(max_length=40, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='sex_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userlist.malefemale', verbose_name='Пол'),
        ),
    ]
